-- SP identity = its application/client id (M2M). Role name must match the identity.
CREATE ROLE "<SP_CLIENT_ID>" LOGIN;
GRANT USAGE ON SCHEMA demo TO "<SP_CLIENT_ID>";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA demo TO "<SP_CLIENT_ID>";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA demo TO "<SP_CLIENT_ID>";
ALTER DEFAULT PRIVILEGES IN SCHEMA demo
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "<SP_CLIENT_ID>";
